### ISSUE TITLE
Bootstrap popover for suggestions

### ISSUE THREAD

**Issue by jqnatividad** [minhajuddin2510/ckanext-scheming#1]
The following suggestion keywords will be added to support DRUF:
* suggestion label: (if not specified, it will use `label` for the current field
* suggestion formula: the jinja2 expression to evaluate

The Bootstrap popover button should use this icon
https://thenounproject.com/icon/effects-3689195/

With a hover title "formula" - with a green hued button to indicate that there is a suggestion for the associated field.

For example:
```yaml
scheming_version: 2
dataset_type: dataset
about: A reimplementation of the default CKAN dataset schema
about_url: http://github.com/ckan/ckanext-scheming


dataset_fields:

- field_name: title
  label: Title
  preset: title
  form_placeholder: eg. A descriptive title Custom

- field_name: name
  label: URL
  preset: dataset_slug
  form_placeholder: eg. my-dataset

- field_name: notes
  label: Description
  form_snippet: markdown.html
  form_placeholder: eg. Some useful notes/blurb about the data
  # suggest_jinja2: Latitudinal range {{LATITUDE.stats.max|float - LATITUDE.stats.min|float }}

- field_name: spatial_extent
  label: Spatial Extent
  form_snippet: markdown.html
  suggestion table: Spatial Extent Blah
  suggestion formula: POLYGON(({{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.min|float}}, {{LATITUDE.stats.max|float}}, {{LONGITUDE.stats.min|float}}, {{LATITUDE.stats.max|float}}, {{LONGITUDE.stats.max|float}}, {{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.max|float}}, {{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.min|float}}))

- field_name: test_field
  label: Test Field
  form_snippet: markdown.html
  suggest_jinja2: '{{package.author}}: {{package.author_email}}'

- field_name: tag_string
  label: Tags
  preset: tag_string_autocomplete
  form_placeholder: eg. economy, mental health, government

- field_name: license_id
  label: License
  form_snippet: license.html
  help_text: License definitions and additional information can be found at http://opendefinition.org/

- field_name: owner_org
  label: Organization
  preset: dataset_organization

- field_name: url
  label: Source
  form_placeholder: http://example.com/dataset.json
  display_property: foaf:homepage
  display_snippet: link.html

- field_name: version
  label: Version
  validators: ignore_missing unicode_safe package_version_validator
  form_placeholder: '1.0'

- field_name: author
  label: Author
  form_placeholder: Joe Bloggs
  display_property: dc:creator

- field_name: author_email
  label: Author Email
  form_placeholder: joe@example.com
  display_property: dc:creator
  display_snippet: email.html
  display_email_name_field: author

- field_name: maintainer
  label: Maintainer
  form_placeholder: Joe Bloggs
  display_property: dc:contributor

- field_name: maintainer_email
  label: Maintainer Email
  form_placeholder: joe@example.com
  display_property: dc:contributor
  display_snippet: email.html
  display_email_name_field: maintainer


resource_fields:

- field_name: url
  label: URL
  preset: resource_url_upload

- field_name: name
  label: Name
  form_placeholder: eg. January 2011 Gold Prices

- field_name: description
  label: Description
  form_snippet: markdown.html
  form_placeholder: Some useful notes about the data

- field_name: spatial_extent
  label: Spatial Extent
  form_snippet: markdown.html
  suggest_jinja2: POLYGON(({{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.min|float}}, {{LATITUDE.stats.max|float}}, {{LONGITUDE.stats.min|float}}, {{LATITUDE.stats.max|float}}, {{LONGITUDE.stats.max|float}}, {{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.max|float}}, {{LATITUDE.stats.min|float}}, {{LONGITUDE.stats.min|float}}))


- field_name: format
  label: Format
  preset: resource_format_autocomplete

```
